[program:gamma]

user=www-data
command=/edx/app/gamma/venv/bin/gunicorn -b :9000 gamma.wsgi
directory=/edx/app/gamma/gamma
autorestart=true
redirect_stderr=true
stdout_logfile=/edx/var/log/supervisor/%(program_name)s-stdout.log
stderr_logfile=/edx/var/log/supervisor/%(program_name)s-stderr.log
stopsignal=KILL
killasgroup=true
stopasgroup=true

[program:gamma_worker]

user=www-data
command=/edx/app/gamma/venv/bin/python /edx/app/gamma/gamma/manage.py celery worker --loglevel=info --queues=gamma --hostname=localhost --concurrency=1
directory=/edx/app/gamma/gamma
autorestart=true
redirect_stderr=true
stdout_logfile=/edx/var/log/supervisor/%(program_name)s-stdout.log
stderr_logfile=/edx/var/log/supervisor/%(program_name)s-stderr.log
stopsignal=KILL
killasgroup=true
stopasgroup=true
