"""
Ranking override for the Subtitle Superhero badge's own leaderboard.

Everyone holding that badge earned the same points for it, so ordering its board by total
points says nothing about who did the subtitle work. Its earners are instead ordered (and shown) by
the number of subtitle lines they contributed (insertions + deletions on ``.srt``/``.sbv``
files in the opensecuritytraining GitLab repos), generated by
``subtitle-research/subtitle_line_counts.py`` and mapped to usernames by
``subtitle-research/subtitle_lines_to_usernames.py``.
"""
import json
import os
from functools import lru_cache
from typing import Dict

SUBTITLE_SUPERHERO_SLUG = "subtitle-superhero"
LINES_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "subtitle_superhero_lines.json")


@lru_cache(maxsize=1)
def get_subtitle_lines() -> Dict[str, int]:
    """
    Provide the ``user_uid`` -> subtitle lines changed mapping (empty if the file is missing).
    """
    try:
        with open(LINES_FILE, encoding="utf-8") as lines_file:
            return {str(uid): int(lines) for uid, lines in json.load(lines_file).items()}
    except (OSError, ValueError):
        return {}


def has_custom_ranking(badge_slug: str) -> bool:
    """
    Whether the badge's board is ranked by subtitle lines instead of points.
    """
    return badge_slug == SUBTITLE_SUPERHERO_SLUG


SCORE_LABEL = "Subtitle Lines Changed"


def get_score_label(badge_slug: str):
    """
    Provide the column header for the board's score when it is not "Total Points" (else ``None``).
    """
    return SCORE_LABEL if has_custom_ranking(badge_slug) else None
