# Generated by Django 3.2.25 on 2025-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GammaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('signup_source', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('chart', models.JSONField(blank=True, default=dict)),
                ('progress', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
