# Generated by Django 3.2.25 on 2025-01-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gammauser',
            options={'verbose_name': 'Gamma User', 'verbose_name_plural': 'Gamma Users'},
        ),
    ]
