# Generated by Django 3.2.25 on 2025-04-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_gammauser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GammaUserCoursePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('gamma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_points', to='users.gammauser')),
            ],
            options={
                'verbose_name': 'Gamma User course points',
                'verbose_name_plural': "Gamma User courses' points",
                'unique_together': {('gamma_user', 'course_id')},
            },
        ),
    ]
