# Generated by Django 3.2.25 on 2025-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gammausercoursepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammauser',
            name='is_demo_user',
            field=models.BooleanField(default=False),
        ),
    ]
