# Generated by Django 3.2.25 on 2026-06-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_gammauser_continuous_learning_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gammauser',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
