# Generated by Django 3.2.25 on 2025-01-02 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('signup_source', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(db_column='user_uid', max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=32)),
                ('award', models.PositiveSmallIntegerField(verbose_name='Points to award')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Applied Blue'), (2, 'Green'), (3, 'Yellow'), (4, 'Orange'), (5, 'Bright Blue'), (6, 'Purple'), (7, 'Light Gray'), (8, 'Red')], default=1)),
                ('notification_message', models.CharField(default='You have got {} point.', help_text="\nYou can use {} to insert awarded points into correct place. e.g. Congrats! You've earned {} points for watching videos\n", max_length=128)),
            ],
        ),
    ]
