# Generated by Django 3.2.25 on 2025-01-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20250102_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_config',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.CharField(db_column='user_uid', default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
