# Generated by Django 3.2.25 on 2025-01-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20250102_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('uid', 'client', 'username')},
        ),
    ]
