# Generated by Django 3.2.25 on 2025-01-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Allowed events')),
            ],
        ),
        migrations.AlterField(
            model_name='eventconfiguration',
            name='event_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype'),
        ),
    ]
