# Generated by Django 3.2.25 on 2025-01-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20250102_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='points',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.eventconfiguration'),
        ),
        migrations.AlterField(
            model_name='eventconfiguration',
            name='event_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='events.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(help_text="Defines a unique event type allowed in the system, such as 'stop_video' or 'edx.bookmark.added'", max_length=255, unique=True),
        ),
    ]
