# Generated by Django 3.2.25 on 2025-02-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0006_auto_20250117_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfiguration',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='eventconfiguration',
            name='is_depends_on_achievement',
            field=models.BooleanField(default=False, help_text='Indicates whether the event is used to validate achievement dependencies'),
        ),
    ]
