# Generated by Django 3.2.25 on 2025-04-22 09:52

from django.db import migrations, models
import events.utils


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20250203_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.CharField(default=events.utils.uid_generator, max_length=255),
        ),
    ]
