# Generated by Django 3.2.25 on 2025-05-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventconfiguration',
            name='color',
        ),
        migrations.RemoveField(
            model_name='eventconfiguration',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='eventconfiguration',
            name='notification_message',
        ),
    ]
