# Generated by Django 3.2.25 on 2025-05-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20250508_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventconfiguration',
            name='is_depends_on_achievement',
        ),
    ]
