before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - tag
  - cleanup

variables:
    TEST_IMAGE: $CI_REGISTRY_IMAGE/app-test
    TEST_IMAGE_STATIC: $CI_REGISTRY_IMAGE/app-test-static

services:
  - docker:20.10.16-dind


Build:
  stage: build
  tags:
    - dind
  only:
    - master
    - merge_requests
  script:
    - docker pull $TEST_IMAGE || true
    - docker build -t $TEST_IMAGE --cache-from $TEST_IMAGE --push .

BuildStatic:
  stage: build
  tags:
    - dind
  only:
    - master
    - merge_requests
  script:
    - docker pull $TEST_IMAGE_STATIC || true
    - docker build --target=static -t $TEST_IMAGE_STATIC --cache-from $TEST_IMAGE_STATIC --push .

ReactTests:
  variables:
    GIT_STRATEGY: none
  stage: test
  tags:
    - dind
  only:
    - master
    - merge_requests
  script:
    - docker pull $TEST_IMAGE_STATIC || true
    - docker run
      --rm
      $TEST_IMAGE_STATIC
      bash -c "npm run test ./frontend/admin-panel/src"
  after_script:
    - docker rmi -f $TEST_IMAGE_STATIC || true

Tests:
  variables:
    GIT_STRATEGY: none
  stage: test
  tags:
    - dind
  only:
    - master
    - merge_requests
  script:
    - docker pull $TEST_IMAGE || true
    - docker run -d --name mongo_$CI_COMMIT_SHORT_SHA mongo:4.2
    - docker run -d --name redis_$CI_COMMIT_SHORT_SHA redis:latest
    - docker run
      --rm
      -e MONGO_URL=mongodb://mongo:27017/
      -e MONGO_DATABASE=gamma_data_test
      -e DJANGO_SETTINGS_MODULE=gamma.settings.test
      --link mongo_$CI_COMMIT_SHORT_SHA:mongo
      --link redis_$CI_COMMIT_SHORT_SHA:redis
      $TEST_IMAGE
      bash -c "pytest && coverage xml && diff-cover coverage.xml --fail-under=60"
  after_script:
    - docker rm -f mongo_$CI_COMMIT_SHORT_SHA || true
    - docker rm -f redis_$CI_COMMIT_SHORT_SHA || true
    - docker rmi -f $TEST_IMAGE || true

Tag:
  stage: tag
  tags:
    - dind
  only:
    - master
  script:
    - docker pull $TEST_IMAGE || true
    - docker tag $TEST_IMAGE $CI_REGISTRY_IMAGE/app
    - docker push $CI_REGISTRY_IMAGE/app
  after_script:
    - docker rmi -f $TEST_IMAGE || true

Cleanup:
  stage: cleanup
  tags:
    - dind
  only:
    - master
    - merge_requests
  when: always
  script:
    - docker rmi -f $TEST_IMAGE || true
