before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - tag
  - cleanup


Build:
  stage: build
  tags:
    - dind
  only:
    - master
    - merge_requests
  script:
    - docker build -t $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHORT_SHA .

Tests:
  variables:
    GIT_STRATEGY: none
  stage: test
  tags:
    - dind
  only:
    - master
    - merge_requests
  script:
    - docker run -d --name mongo_$CI_COMMIT_SHORT_SHA mongo:4.2
    - docker run
      --rm
      --link mongo_$CI_COMMIT_SHORT_SHA:mongo
      $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHORT_SHA
      bash -c "pytest && coverage xml && diff-cover coverage.xml --fail-under=60"
  after_script:
    - docker rm -f mongo_$CI_COMMIT_SHORT_SHA || true

Tag:
  stage: tag
  tags:
    - dind
  only:
    - master
  script:
    - docker tag $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/app
    - docker push $CI_REGISTRY_IMAGE/app
  after_script:
    - docker rmi -f $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHORT_SHA || true

Cleanup:
  stage: cleanup
  tags:
    - dind
  only:
    - master
    - merge_requests
  when: always
  script:
    - docker rmi -f $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHORT_SHA || true
