before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - tag
  - cleanup

variables:
    TEST_IMAGE: $CI_REGISTRY_IMAGE/app-test
    TEST_IMAGE_STATIC: $CI_REGISTRY_IMAGE/app-test-static

services:
  - docker:20.10.16-dind

.build:
  stage: build
  tags:
    - k8s-kaniko
  variables:
    KUBERNETES_CPU_REQUEST: "1200m"
    KUBERNETES_CPU_LIMIT: "2500m"
    KUBERNETES_MEMORY_REQUEST: "2Gi"
    KUBERNETES_MEMORY_LIMIT: "3Gi"
  only:
    - master
    - merge_requests
  before_script: []
  script:
    # Build docker image
    -  sed -i -e '$a!.git/' .dockerignore
    -  mkdir -p /kaniko/.docker
    -  echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN
      --build-arg node_env=$node_env
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${BASE_IMAGE}"
      --cache=true
      --use-new-run
      --target ${DOCKER_TARGET}

BuildTest:
  extends: .build
  variables:
    BASE_IMAGE: $TEST_IMAGE
    DOCKER_TARGET: development
    node_env: dev

BuildStatic:
  extends: .build
  variables:
    BASE_IMAGE: $TEST_IMAGE_STATIC
    DOCKER_TARGET: static
    node_env: dev

ReactTests:
  stage: test
  tags:
    - k8s-runner
  variables:
    KUBERNETES_CPU_REQUEST: "500m"
    KUBERNETES_CPU_LIMIT: "1000m"
    KUBERNETES_MEMORY_REQUEST: "2Gi"
    KUBERNETES_MEMORY_LIMIT: "3Gi"
  image: $TEST_IMAGE_STATIC
  only:
    - master
    - merge_requests
  before_script: []
  script:
    - npm run --prefix /app/frontend/gamma test ./frontend/gamma

Tests:
  stage: test
  tags:
    - k8s-runner
  image: $TEST_IMAGE
  only:
    - master
    - merge_requests
  variables:
    MONGO_URL: mongodb://mongodb:27017/
    MONGO_DATABASE: gamma_data_test
    DJANGO_SETTINGS_MODULE: gamma.settings.test
  services:
    - name: mongo:4.4
      alias: mongodb
    - name: redis:latest
      alias: redis
  before_script: []
  script:
    - pytest && coverage xml && diff-cover coverage.xml --fail-under=60

Tag:
  stage: tag
  tags:
    - dind
  only:
    - master
  script:
    - docker pull $TEST_IMAGE || true
    - docker tag $TEST_IMAGE $CI_REGISTRY_IMAGE/app
    - docker push $CI_REGISTRY_IMAGE/app
  after_script:
    - docker rmi -f $TEST_IMAGE || true

Cleanup:
  stage: cleanup
  tags:
    - dind
  only:
    - master
    - merge_requests
  when: always
  script:
    - docker rmi -f $TEST_IMAGE || true
