version: '3.5'

services:

  traefik:
    restart: unless-stopped
    image: traefik:v2.2
    container_name: gamma_traefik
    ports:
      - 9000:80
      - 8080:8080
    volumes:
      - .conf/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dashboard:
    restart: unless-stopped
    container_name: gamma_dashboard
    build:
      context: .
      target: development
      args:
        - node_env=dev
    env_file:
      - ./envs/base.env
      - ./envs/private.env
    command: "gunicorn --config .conf/gunicorn/gunicorn.conf.py -b :8000 --access-logfile - --error-logfile - --log-file - --capture-output --log-level warning gamma.wsgi"
    volumes:
      - static_files:/app/gamma/static/
      - media_files:/app/gamma/media/
    expose:
      - "8000"
    links:
      - mongo
      - postgres
      - celery_worker
      - celery_beat
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.rule=Host(`${HOST:-localhost}`) || Host(`${GAMMA_CUSTOM_DOMAIN}`)"
      - "traefik.http.routers.app-https.entrypoints=websecure"
      - "traefik.http.routers.app-https.rule=Host(`${HOST:-localhost}`) || Host(`${GAMMA_CUSTOM_DOMAIN}`)"
      - "traefik.http.routers.app-https.tls.certresolver=mytlschallenge"

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: gamma_nginx
    links:
      - dashboard
    volumes:
      - .conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/static
      - media_files:/media
    labels:
        - "traefik.enable=true"
        - "traefik.backend=nginx"
        - "traefik.port=9000"
        - "traefik.http.routers.static-http.entrypoints=web"
        - "traefik.http.routers.static-http.rule=(Host(`${HOST:-localhost}`) || Host(`${GAMMA_CUSTOM_DOMAIN}`)) && PathPrefix(`/static`) || PathPrefix(`/media`)"
        - "traefik.http.routers.static-https.entrypoints=websecure"
        - "traefik.http.routers.static-https.rule=(Host(`${HOST:-localhost}`) || Host(`${GAMMA_CUSTOM_DOMAIN}`)) && PathPrefix(`/static`) || PathPrefix(`/media`)"
        - "traefik.http.routers.static-https.tls.certresolver=mytlschallenge"
    expose:
      - "9000"

  celery_worker: &celery_worker
    restart: unless-stopped
    container_name: gamma_celery_worker
    build:
      context: .
      target: base
    command: celery worker -A gamma --loglevel=INFO
    env_file:
      - ./envs/base.env
      - ./envs/private.env
    links:
      - rabbit
      - redis

  celery_beat:
    <<: *celery_worker
    container_name: gamma_celery_beat
    command: celery beat -A gamma --loglevel=INFO

  mongo:
    restart: unless-stopped
    container_name: gamma_mongo
    image: mongo:4.2
    volumes:
      - mongo_db:/data/db

  postgres:
    restart: unless-stopped
    container_name: gamma_postgres
    image: postgres:12.1
    env_file:
      - ./envs/base.env
      - ./envs/private.env
    volumes:
        - pg_db:/var/lib/postgresql/data/

  rabbit:
    restart: unless-stopped
    container_name: gamma_rabbit
    image: rabbitmq:latest

  redis:
    restart: unless-stopped
    container_name: gamma_redis
    image: redis:latest

volumes:
  pg_db:
  mongo_db:
  static_files:
  media_files:
