version: '3'

services:

  dashboard:
    container_name: gamma_dashboard
    build: .
    env_file:
      - ./envs/local.env
      - ./envs/private.env
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    links:
      - mongo
      - postgres
      - celery

  celery:
    container_name: gamma_celery
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery worker -A gamma --loglevel=INFO -B
    env_file:
      - ./envs/local.env
      - ./envs/private.env
    volumes:
      - .:/app
    links:
      - rabbit
      - redis

  mongo:
    container_name: gamma_mongo
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  postgres:
    container_name: gamma_postgres
    image: postgres:12.1
    env_file:
      - ./envs/local.env
      - ./envs/private.env
    volumes:
        - pg_db:/var/lib/postgresql/data/

  rabbit:
    container_name: gamma_rabbit
    image: rabbitmq:latest
  
  redis:
    container_name: gamma_redis
    image: redis:latest

volumes:
  pg_db:
  mongo_db:
