FROM python:3.6-slim
LABEL maintainer="cmltaWt0@gmail.com"

RUN apt-get -y update && \
    apt-get install -y \
    gcc python-dev zlib1g-dev libjpeg-dev

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

RUN mkdir /requirements
ADD ./requirements/* /requirements/

WORKDIR /requirements
RUN pip install -r dev.txt


RUN { \
	echo 'import os'; \
	echo "BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://')"; \
} > celeryconfig.py

# --link some-rabbit:rabbit "just works"
ENV CELERY_BROKER_URL amqp://guest@rabbit

USER user
WORKDIR /home/user/app
CMD ["celery", "worker"]
