[pytest]
addopts =
    --cov=.
    --cov-report term-missing
    --cov-config .coveragerc
    --ignore=.conf/
    --nomigrations
    --reuse-db
norecursedirs = node_modules
python_files = test_*.py
DJANGO_SETTINGS_MODULE = gamma.settings.test

markers =
    unittests: marks tests as unit test
