[pytest]
addopts =
    --cov=.
    --cov-report term-missing
    --cov-config .coveragerc
    --ignore=.conf/
    --ignore=loadtests/
    --ignore=core/tests/test_api.py
    --ignore=core/tests/test_data.py
    --ignore=core/tests/test_forms.py
    --ignore=core/tests/test_integrate.py
    --ignore=core/tests/test_mongo.py
    --ignore=core/tests/test_utils.py
    --nomigrations
    --reuse-db
norecursedirs = node_modules
python_files = test_*.py
DJANGO_SETTINGS_MODULE = gamma.settings.test

markers =
    unittests: marks tests as unit test
