[pytest]
addopts = --cov=. --cov-report term-missing --cov-config .coveragerc --ignore=.conf/ --ignore=loadtests/ --nomigrations --reuse-db
norecursedirs = node_modules
python_files = *.py
DJANGO_SETTINGS_MODULE = gamma.settings.test
