# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
