# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 10:40
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20160908_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='badge_image',
        ),
        migrations.AddField(
            model_name='achievement',
            name='badge_img',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name=b'Image'),
        ),
    ]
