# Generated by Django 3.0.5 on 2020-05-09 18:09

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20200228_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user_uid',
            field=models.CharField(default='max', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatus',
            name='user_uid',
            field=models.CharField(default='max', max_length=128),
            preserve_default=False,
        ),
    ]
