# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20160909_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_type',
            field=models.CharField(choices=[(b'video', b'video'), (b'problem', b'problem'), (b'course', b'course'), (b'enrollment', b'enrollment')], max_length=64),
        ),
    ]
