# Generated by Django 3.0.6 on 2020-05-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20200509_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='status',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
