# Generated by Django 3.0.7 on 2020-07-13 05:50

import django.core.validators
from django.db import migrations, models
from django.db.models import Q


def prepopulate_null_or_zero_status_points(apps, schema_editor):
    StatusBadge = apps.get_model('achievements', 'StatusBadge')

    empty_or_zero_points = StatusBadge.objects.filter(Q(status_points=0) | Q(status_points__isnull=True))

    for sb in empty_or_zero_points:
        sb.status_points = sb.id
        sb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_auto_20200517_1419'),
    ]

    operations = [
        migrations.RunPython(prepopulate_null_or_zero_status_points),

        migrations.AlterField(
            model_name='statusbadge',
            name='status_points',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
