# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_auto_20160914_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_img',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='badge_type',
            field=models.CharField(choices=[('video', 'video'), ('problem', 'problem'), ('course', 'course'), ('enrollment', 'enrollment'), ('referrer', 'referrer')], max_length=64),
        ),
    ]
