# Generated by Django 3.0.14 on 2022-04-12 12:42

import achievements.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_auto_20200713_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_img',
            field=achievements.fields.CustomImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='statusbadge',
            name='badge_img',
            field=achievements.fields.CustomImageField(upload_to='media'),
        ),
    ]
