# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
        ('achievements', '0005_auto_20160919_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Event', verbose_name='Related event'),
        ),
    ]
