# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_achievement_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_type',
            field=models.CharField(choices=[(b'video', b'video'), (b'problem', b'problem'), (b'course', b'course'), (b'enrollment', b'enrollment'), (b'referrer', b'referrer'), (b'reward', b'reward')], max_length=64),
        ),
    ]
