# Generated by Django 3.2.25 on 2025-01-09 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('rules', '0001_initial'),
        ('achievements', '0006_auto_20220412_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='StatusBadge',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='badge_id',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='badge_img',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='slug',
        ),
        migrations.AddField(
            model_name='achievement',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.gammauser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='achievementrule',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_rules', to='achievements.achievement'),
        ),
        migrations.AddField(
            model_name='achievementrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_achievements', to='rules.rule'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementrule',
            unique_together={('achievement', 'rule')},
        ),
    ]
