# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_auto_20161019_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='status_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='status_color',
            field=models.CharField(blank=True, choices=[(b'blue', b'blue'), (b'yellow', b'yellow'), (b'red', b'red')], max_length=16),
        ),
        migrations.AddField(
            model_name='achievement',
            name='status_points',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='badge_type',
            field=models.CharField(choices=[(b'video', b'video'), (b'problem', b'problem'), (b'course', b'course'), (b'enrollment', b'enrollment'), (b'referrer', b'referrer'), (b'reward', b'reward'), (b'status', b'status')], max_length=64),
        ),
    ]
