# Generated by Django 3.2.25 on 2025-01-22 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_auto_20250109_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementrule',
            name='actual_count',
            field=models.JSONField(default=dict, help_text="Tracks the current progress for each related event, e.g. {'stop_video': 1}."),
        ),
        migrations.AddField(
            model_name='achievementrule',
            name='dependencies',
            field=models.JSONField(default=dict, help_text="Stores additional requirements needed to complete this rule, such as {'badge': '101'}."),
        ),
        migrations.AlterField(
            model_name='achievementrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
