# Generated by Django 2.1.7 on 2019-03-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_auto_20161027_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_type',
            field=models.CharField(choices=[('video', 'video'), ('problem', 'problem'), ('course', 'course'), ('enrollment', 'enrollment'), ('referrer', 'referrer'), ('reward', 'reward'), ('status', 'status')], max_length=64),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Event', verbose_name='Related event'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='status_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('yellow', 'yellow'), ('red', 'red')], max_length=16),
        ),
    ]
