# Generated by Django 3.2.25 on 2025-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_auto_20250122_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementrule',
            name='actual_count',
        ),
        migrations.AlterField(
            model_name='achievementrule',
            name='dependencies',
            field=models.JSONField(default=dict, help_text='Tracks the current progress for external events and achievement dependencies based on rules action'),
        ),
    ]
