# Generated by Django 2.1.7 on 2019-03-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_auto_20190305_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='badge_type',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='event',
        ),
    ]
