# Generated by Django 3.2.25 on 2025-05-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_auto_20250130_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementrule',
            name='points',
        ),
    ]
