# Generated by Django 2.1.7 on 2019-03-12 11:50

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_auto_20190310_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('badge_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('status_points', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('status_color', models.CharField(blank=True, choices=[('blue', 'blue'), ('yellow', 'yellow'), ('red', 'red')], max_length=16)),
                ('badge_img', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image')),
            ],
        ),
    ]
