# Generated by Django 2.1.7 on 2019-03-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0012_userstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(blank=True, max_length=16)),
                ('award', models.PositiveSmallIntegerField(verbose_name='Points to award')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Applied Blue'), (2, 'Green'), (3, 'Yellow'), (4, 'Orange'), (5, 'Bright Blue'), (6, 'Purple'), (7, 'Light Gray'), (8, 'Red')], default=1)),
                ('notification_message', models.CharField(default='You have got {} point.', help_text="You can use {} to insert awarded points into correct place. e.g. Congrats! You've earned {} points for watching videos", max_length=128)),
            ],
        ),
    ]
