# Generated by Django 2.1.7 on 2019-03-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0013_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='status_badge',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='status_color',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='status_points',
        ),
    ]
