# Generated by Django 2.1.7 on 2019-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0014_auto_20190312_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='statusbadge',
            name='badge_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
