# Generated by Django 2.1.7 on 2019-08-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0015_auto_20190326_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
