# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 13:53
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('key', models.CharField(db_index=True, default=core.utils.key_secret_generator, max_length=32, unique=True)),
                ('secret', models.CharField(default=core.utils.key_secret_generator, max_length=32, unique=True)),
            ],
        ),
    ]
