# Generated by Django 3.0.5 on 2020-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='user_uid',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
