# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=16, unique=True)),
                ('award', models.PositiveSmallIntegerField(verbose_name='Points to award')),
            ],
        ),
    ]
