# Generated by Django 3.0.6 on 2020-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200509_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appclient',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
