# Generated by Django 3.0.6 on 2020-05-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200511_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameProfile',
        ),
    ]
