# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
