# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='order',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Applied Blue'), (2, b'Green'), (3, b'Yellow'), (4, b'Orange'), (5, b'Bright Blue'), (6, b'Purple'), (7, b'Light Gray'), (8, b'Red')], default=1),
        ),
    ]
