# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161109_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_message',
            field=models.CharField(default=b'You have got {} point.', help_text=b"You can use {} to insert awarded points into correct place. e.g. Congrats! You've earned {} points for watching videos", max_length=128),
        ),
    ]
