# Generated by Django 2.1.7 on 2019-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Applied Blue'), (2, 'Green'), (3, 'Yellow'), (4, 'Orange'), (5, 'Bright Blue'), (6, 'Purple'), (7, 'Light Gray'), (8, 'Red')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='notification_message',
            field=models.CharField(default='You have got {} point.', help_text="You can use {} to insert awarded points into correct place. e.g. Congrats! You've earned {} points for watching videos", max_length=128),
        ),
    ]
