# Generated by Django 2.1.7 on 2019-03-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190305_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
