# Generated by Django 2.1.7 on 2019-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
