# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appclient'),
        ('pointlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedevent',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AppClient'),
        ),
        migrations.AlterField(
            model_name='loggedevent',
            name='uniq_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='loggedevent',
            unique_together=set([('uniq_id', 'client')]),
        ),
    ]
