# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-21 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedevent',
            name='rewarded_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
