# Generated by Django 3.0.4 on 2020-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedevent',
            name='course_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
