# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0002_auto_20160907_1747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loggedevent',
            unique_together=set([('user', 'uniq_id', 'client')]),
        ),
    ]
