# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0003_auto_20161122_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardAccess',
            new_name='ApiAccessEvent',
        ),
    ]
