# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-24 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0004_auto_20161122_1306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apiaccessevent',
            unique_together=set([('user', 'api_name', 'date')]),
        ),
    ]
