# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0005_auto_20161124_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedevent',
            name='org',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
