# Generated by Django 2.1.7 on 2019-03-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0006_loggedevent_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedevent',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.AppClient'),
        ),
    ]
