# Generated by Django 2.1.7 on 2019-08-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointlog', '0007_auto_20190305_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedevent',
            name='event_type',
            field=models.CharField(max_length=64),
        ),
    ]
