import pytest

from statuses.models import Status


@pytest.mark.django_db
class TestStatusModel:
    """
    Tests for the Status model.
    """

    def test_slug_autogenerated_from_title(self, status_factory):
        status = status_factory(title='Gold Status', slug='')
        assert status.slug == 'gold-status'

    def test_slug_preserved_when_provided(self, status_factory):
        status = status_factory(title='Gold Status', slug='custom-slug')
        assert status.slug == 'custom-slug'

    def test_str(self, status_factory):
        status = status_factory(title='Gold', status_points=220)
        assert str(status) == "Status 'Gold' (220 pts)"

    def test_default_ordering_by_status_points(self, status_factory):
        status_factory(title='High', status_points=600)
        status_factory(title='Low', status_points=100)
        status_factory(title='Mid', status_points=300)

        points = list(Status.objects.values_list('status_points', flat=True))
        assert points == [100, 300, 600]
