# Generated by Django 3.2.25 on 2025-02-21 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0002_auto_20250122_0903'),
        ('users', '0002_alter_gammauser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Avatar Description')),
                ('image', models.FileField(upload_to='uploads/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('rules', models.ManyToManyField(blank=True, to='rules.Rule')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
        migrations.CreateModel(
            name='AvatarSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar Set Title')),
                ('use_in_courses', models.JSONField(default=list)),
                ('is_draft', models.BooleanField(default=True)),
                ('avatars', models.ManyToManyField(blank=True, to='avatars.Avatar', verbose_name='Avatars')),
            ],
            options={
                'verbose_name': 'Avatar Set',
                'verbose_name_plural': 'Avatar Sets',
            },
        ),
        migrations.CreateModel(
            name='UserAvatarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avatars.avatarset')),
                ('selected_avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avatars.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gammauser')),
            ],
            options={
                'verbose_name': 'User Avatar Config',
                'verbose_name_plural': 'User Avatar Configs',
            },
        ),
    ]
