# Generated by Django 3.2.25 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0002_auto_20250306_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='stage',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
