# Generated by Django 3.2.25 on 2025-04-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gammausercoursepoints'),
        ('avatars', '0003_avatar_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatarconfig',
            name='selected_avatar',
        ),
        migrations.AlterField(
            model_name='useravatarconfig',
            name='avatar_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatars.avatarset'),
        ),
        migrations.AlterField(
            model_name='useravatarconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.gammauser'),
        ),
    ]
