# Generated by Django 3.2.25 on 2025-05-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0004_auto_20250414_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatarset',
            name='use_in_courses',
        ),
    ]
