# Generated by Django 3.2.25 on 2025-11-26 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0005_remove_avatarset_use_in_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='stage',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Avatar Stage'),
        ),
    ]
