# Generated by Django 3.2.25 on 2025-01-23 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_gammauser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Base Name')),
                ('base_image', models.FileField(blank=True, null=True, upload_to='static/images/avatar_bases/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
            ],
            options={
                'verbose_name': 'Avatar Base',
                'verbose_name_plural': 'Avatar Bases',
            },
        ),
        migrations.CreateModel(
            name='AvatarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Color Name')),
                ('hex_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a valid hex color code')], verbose_name='Hex Color Code')),
            ],
            options={
                'verbose_name': 'Avatar Color',
                'verbose_name_plural': 'Avatar Colors',
            },
        ),
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('svg_file', models.FileField(blank=True, null=True, upload_to='static/images/avatar_items/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
            ],
            options={
                'verbose_name': 'Avatar Item',
                'verbose_name_plural': 'Avatar Items',
            },
        ),
        migrations.CreateModel(
            name='AvatarSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Set Name')),
                ('avatar_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar.avatarcolor', verbose_name='Avatar Color')),
            ],
            options={
                'verbose_name': 'Avatar Set',
                'verbose_name_plural': 'Avatar Sets',
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Skin Type')),
            ],
            options={
                'verbose_name': 'Skin Type',
                'verbose_name_plural': 'Skin Types',
            },
        ),
        migrations.CreateModel(
            name='UserAvatarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/images/user_avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'heic'])])),
                ('use_avatar', models.BooleanField(default=False, verbose_name='Use this avatar?')),
                ('avatar_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar.avatarset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.gammauser')),
            ],
            options={
                'verbose_name': 'User Avatar Config',
                'verbose_name_plural': 'User Avatar Configs',
            },
        ),
        migrations.CreateModel(
            name='AvatarSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.avatarbase')),
                ('avatar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.avataritem')),
            ],
            options={
                'verbose_name': 'Avatar Set Item',
                'verbose_name_plural': 'Avatar Set Items',
                'unique_together': {('avatar_base', 'avatar_item')},
            },
        ),
        migrations.AddField(
            model_name='avatarset',
            name='avatar_items',
            field=models.ManyToManyField(blank=True, to='avatar.AvatarSetItem', verbose_name='Avatar Items'),
        ),
        migrations.AddField(
            model_name='avatarset',
            name='base_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar.avatarbase', verbose_name='Base Image'),
        ),
        migrations.AddField(
            model_name='avataritem',
            name='skin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.skintype'),
        ),
    ]
