# Generated by Django 3.2.25 on 2025-02-13 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20250122_0903'),
        ('users', '0002_alter_gammauser_options'),
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Avatar Description')),
                ('image', models.FileField(upload_to='uploads/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('rules', models.ManyToManyField(blank=True, to='rules.Rule')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
        migrations.RemoveField(
            model_name='avataritem',
            name='skin_type',
        ),
        migrations.AlterUniqueTogether(
            name='avatarsetitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='avatarsetitem',
            name='avatar_base',
        ),
        migrations.RemoveField(
            model_name='avatarsetitem',
            name='avatar_item',
        ),
        migrations.RemoveField(
            model_name='avatarset',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='avatarset',
            name='avatar_items',
        ),
        migrations.RemoveField(
            model_name='avatarset',
            name='base_image',
        ),
        migrations.RemoveField(
            model_name='avatarset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useravatarconfig',
            name='image',
        ),
        migrations.RemoveField(
            model_name='useravatarconfig',
            name='use_avatar',
        ),
        migrations.AddField(
            model_name='avatarset',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avatarset',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar Set Title'),
        ),
        migrations.AddField(
            model_name='avatarset',
            name='use_in_courses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='useravatarconfig',
            name='avatar_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar.avatarset'),
        ),
        migrations.AlterField(
            model_name='useravatarconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gammauser'),
        ),
        migrations.DeleteModel(
            name='AvatarBase',
        ),
        migrations.DeleteModel(
            name='AvatarColor',
        ),
        migrations.DeleteModel(
            name='AvatarItem',
        ),
        migrations.DeleteModel(
            name='AvatarSetItem',
        ),
        migrations.DeleteModel(
            name='SkinType',
        ),
        migrations.AddField(
            model_name='avatarset',
            name='avatar',
            field=models.ManyToManyField(blank=True, to='avatar.Avatar', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='useravatarconfig',
            name='selected_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar.avatar'),
        ),
    ]
