SVG_EXTENSION = 'svg'

INVALID_FILE_FORMAT = 'Invalid file format. File should be encoded in base64.'
AVATAR_TITLE_ERROR = 'Each Avatar must have a title.'
AVATAR_STAGES_ERROR = 'At least two Avatar Stages are required.'
AVATAR_SET_TITLE_ERROR = 'Avatar Set Title cannot be empty.'
AVATAR_SET_DUPLICATE_TITLE_ERROR = 'An Avatar Set with this Title already exists.'
AVATAR_SHOULD_CONTAINS_AT_LEAST_ONE_RULE = 'At least one rule should be setup for the Avatar.'
AVATAR_SET_FINISH_SUCCESS = 'AvatarSet has been finished successfully.'
AVATAR_SET_FINISH_FAILURE = 'AvatarSet must contain at least two avatars before finishing.'
