# Generated by Django 3.2.25 on 2025-01-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20250117_1119'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='event_type',
        ),
        migrations.AddField(
            model_name='rule',
            name='event_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='events.eventconfiguration'),
        ),
    ]
