# Generated by Django 3.2.25 on 2025-03-06 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20250212_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
