# Generated by Django 3.2.25 on 2026-06-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_badge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='points',
            field=models.IntegerField(default=0, help_text='Points granted to a user when this badge is manually assigned to them by an admin. May be negative to apply a penalty — only allowed on manually-assigned (rule-less) badges.'),
        ),
    ]
