# Generated by Django 3.2.25 on 2026-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_badge_excluded_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Downscaled copy of the image, generated automatically whenever the image changes and served wherever badges are rendered as icons (the leaderboards). Not edited directly; run the generate_badge_thumbnails command to (re)build them in bulk.', null=True, upload_to='uploads/badges/thumbs/'),
        ),
    ]
